### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by htZhang25** [rafaelvalle/asrgen#1]
Can you tell me which datasets should be used to train the speaker recognition system while there is a folder named 'data_16khz',  and I doubt it contains 100 speakers of 2004 NIST and 1 speaker of 2013 Blizzard and I don't know is this enough? or maybe I don't get the complete audios of each speaker which makes the accuracy of sr is extremely low? Where can I get complete dataset for the speaker recognition system.Thanks.

**Comment by rafaelvalle** [comment]
We used a subset of the NIST 2004 dataset. Please check our paper for a full description.
https://arxiv.org/pdf/1801.02384.pdf

**Comment by htZhang25** [comment]
Thank you.And as a matter of fact,the 82rd line in sr_train.py omits an '+'in front of the '='.I added it and got ideal accuracy eventually.

**Comment by rafaelvalle** [comment]
There should be no need to add the '+' as the accuracy is computed over an entire set.
What accuracy are you getting?

**Comment by htZhang25** [comment]
There is no need in 83rdline instead of 82rd in my view.I got 0.0083,and then 0.83.The iters are 100 exactly.I'm looking forward to your reply.Thanks for your reply.

**Comment by htZhang25** [comment]
There is no need in 83rdline instead of 82rd in my view.I got 0.0083,and then 0.83.The iters are 100 exactly.I'm looking forward to your reply.Thanks for your reply.

**Comment by htZhang25** [comment]
There is no need in 83rdline instead of 82rd in my view.I got 0.0083,and then 0.83.The iters are 100 exactly.I'm looking forward to your reply.Thanks for your reply.

**Comment by htZhang25** [comment]
There is no need in 83rdline instead of 82rd in my view.I got 0.0083,and then 0.83.The iters are 100 exactly.I'm looking forward to your reply.Thanks for your reply.

**Comment by htZhang25** [comment]
There is no need in 83rdline instead of 82rd in my view.I got 0.0083,and then 0.83.The iters are 100 exactly.I'm looking forward to your reply.Thanks for your reply.

**Comment by htZhang25** [comment]
There is no need in 83rdline instead of 82rd in my view.I got 0.0083,and then 0.83.The iters are 100 exactly.I'm looking forward to your reply.Thanks for your reply.

**Comment by htZhang25** [comment]
There is no need in 83rdline instead of 82rd in my view.I got 0.0083,and then 0.83.The iters are 100 exactly.I'm looking forward to your reply.Thanks for your reply.

**Comment by htZhang25** [comment]
There is no need in 83rdline instead of 82rd in my view.I got 0.0083,and then 0.83.The iters are 100 exactly.I'm looking forward to your reply.Thanks for your reply.

**Comment by rafaelvalle** [comment]
Actually, you're correct. There should be a '+=' given that we're taking the average on line 83! Thank you for catching that.

**Comment by htZhang25** [comment]
OK.I am sorry because I am not familiar with the comment operation. I am very happy to get the correct idea.
